### PR TITLE
Allow custom git configuration settings

### PR DESCRIPTION
**Pull request by bencates**

### CODE REVIEW

**Comment by neoziro** [comment]
@bencates why do you need to set config like that? You should put it in your git config.

**Comment by bencates** [comment]
This is necessary in our project to work around a few issues with git-lfs support.  It allows setting git config values *in the build directory* immediately after it is created.  Otherwise we have to let the first deploy on a new machine fail when it tries to clone, cd to the build directory, then set the config flags manually.

**Comment by bencates** [comment]
@neoziro any update on this? Just wanting to make sure the PR doesn't get too out of date if it's something that will be merged.

**Comment by neoziro** [comment]
@timkelty can you merge it?

**Comment by timkelty** [comment]
Apologies, I've been busy.
I'll review this week and merge. @neoziro @bencates

**Pull request merged**
