### PR TITLE
Copy before update

### PR DESCRIPTION
**Pull request by timkelty**
Fixes #20

This is a bit easier now that we have methods to get the previous release.

### CODE REVIEW

**Comment by neoziro** [comment]
@timkelty tests

**Comment by timkelty** [comment]
Added some tests and fixed breaking ones.

**Comment by neoziro** [comment]
@timkelty nice!

**Comment by dr-impossible** [comment]
Hey this new feature copies the old release as a subfolder inside the new release. https://github.com/shipitjs/shipit-deploy/issues/40

**Pull request merged**
