### PR TITLE
Allows deploying without repository url

### PR DESCRIPTION
**Pull request by wujashek**
In some edge cases it's nice to deploy without fetching from repo repository - for example for automation tests, generating source code for deployment etc.
This change allows it with some warning like message for those who accidentally didn't pass repositoryUrl in config.

As a bonus tests regression introduced with rimraf lib are fixed.

### CODE REVIEW

**Comment by lecoueyl** [comment]
Maybe also need to update the REAMDE?
Can't wait for this merge

**Comment by wujashek** [comment]
@lecoueyl to note that repositoryUrl is not required and it can deploy without git repository ?

**Comment by lecoueyl** [comment]
Exxactly, it's better for know that the option is available and that it can deploy from a local

**Comment by wujashek** [comment]
@lecoueyl done, anyone can merge ? please ;)

**Comment by wujashek** [comment]
@neoziro sorry to bother you, you're the last one committing ;) in return for merging this I can check next PR coming in if that helps.

**Comment by neoziro** [comment]
@wujashek I can merge it but v4 is running and it could be removed. I will not release a new version but you could target master.

**Comment by wujashek** [comment]
@neoziro that's fine, thanks !

**Pull request merged**
