### PR TITLE
Pending task

### PR DESCRIPTION
**Pull request by timkelty**
Adds a pending task to compare current git revision to currently deployed revision, and logs the diff to the console.

Note - since this relies on the REVISION file work from https://github.com/shipitjs/shipit-deploy/pull/21, this is branched off that. Once that is merged in I will rebase this from master.

screen shot 2015-03-05 at 11 03 45 am

### CODE REVIEW

**Comment by neoziro** [comment]
@timkelty rebase it please.

**Comment by timkelty** [comment]
All set.

**Comment by neoziro** [comment]
@timkelty no not good, use "rebase" because here there is a lot commits that are not good or duplicated.

**Comment by neoziro** [comment]
@timkelty rebase + push force

**Comment by timkelty** [comment]
Sorry, I thought I did rebase, my bad.
How does that look?

**Pull request merged**
