### PR TITLE
Allow specifying the root drive/folder for RSYNC

### PR DESCRIPTION
**Pull request by vpratfr**
This is in order to get things simple on Windows. Should not affect anything for the other systems.

I have documented the whole process and issues there: https://github.com/shipitjs/shipit-deploy/wiki/Deploying-from-Windows#workspace

I have updated my previous PR according to the latest commit in master.

### CODE REVIEW

**Comment by timkelty** [comment]
I'm not on Windows, so forgive me, just trying to fully understand the issue.

> On one side, shipit will use the current drive letter as the root for folders. On the other side, rsync expects paths with drive letters in them.

I'm not sure what you mean here. Both arguments get passed directly to `rsync`. The only thing `shipit` is doing is prepending `user@server.com:` to you remote path (dest).

When you say "Windows" are you deploying _from_ Windows, _to_ Windows, or both?

**Comment by vpratfr** [comment]
Deploying from Windows 10 to Linux. No worries.

There are two steps currently:

1. Copy the project to a workspace folder and make some stuff in there (git, composer, ...)
2. Rsync with remote server

As explained in the wiki, currently the workspace option is not enough: it makes either of the two steps above fail because the rsync command and the copy command will expect a different format for drive letter (see examples given in the wiki).

So currently, when my setting is right for rsync, the initial copy does not put the project in the right workspace folder. And when the setting is proper for the workspace folder, the argument passed to rsync is not correct so rsync does not find the source workspace folder.

**Comment by timkelty** [comment]
Ok, I'm beginning to understand, thanks.

I'm wondering if the setting should be a little less specific.
E.g. we what if we did:
`shipit.config.copyFrom = shipit.config.workspace`

and used `shipit.config.copyFrom` instead of `shipit.config.workspace` in `remoteCopy`?

**Comment by vpratfr** [comment]
As long as you can pass different values (if required) that would work. 

I think the workspace parameter is fine, and the one we need is specific to rsync, so maybe the name `rsyncFrom` would be less confusing than `copyFrom`.

Then you would use `workspace` as before, and `rsyncFrom` as parameter to the rsync command only.

By default indeed, if not specified, `rsyncFrom` could equal `workspace`.

**Comment by timkelty** [comment]
I'm ok with `rsyncFrom`. I think I like that better than prefixing the path.

**Comment by vpratfr** [comment]
Hi,

I have made the changes you had requested + updated the README accordingly. Do you think this could be merged?

rsyncFrom will be ignored if not specified in the config. If specified it will replace workspace as the source folder for rsync.

**Comment by timkelty** [comment]
@vpratfr Merge in 2.4.0.

**Comment by vpratfr** [comment]
Cool. Thanks.

**Pull request merged**
